version: '3'

services:
  restapi:
    container_name: rest-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - NODE_ENV=development

  mysql:
    container_name: mysql
    image: mysql:5.7
    platform: linux/x86_64
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=restapi
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=password
    volumes:
      - ./mysql:/var/lib/mysql